from returns.result import Failure, Success

from tensora_taco import taco_cli


def test_success():
    result = taco_cli(["y(i) = A(i,j) * x(j)", "-print-nocolor", "-f=A:ds", "-print-compute"])

    isinstance(result, Success)
    assert result.unwrap().startswith("// Generated by the Tensor Algebra Compiler")


def test_failure():
    result = taco_cli(["y(i) = A(i,j) * x(j)", "-print-nocolor", "-f=A:ddd", "-print-compute"])

    assert isinstance(result, Failure)


def test_multiple_kernels():
    result = taco_cli(
        [
            "A(i,k) = B(i,j) * C(j,k)",
            "-print-nocolor",
            "-f=A:ds",
            "-f=B:ds",
            "-f=C:ds",
            "-print-assembly",
            "-print-compute",
            "-print-evaluate",
        ]
    )

    kernel = result.unwrap()

    assert "assemble" in kernel
    assert "compute" in kernel
    assert "evaluate" in kernel
