name: Release

on:
  push:
    tags:
      - 'v*'

env:
  python-version: "3.10"

jobs:
  pypi-publish:
    name: Publish release to PyPI
    runs-on: ubuntu-22.04
    environment: release
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python-version }}
          cache: pip
      - name: Install environment
        run: pip install build==1.0.3
      - name: Build release with Setuptools
        run: python -m build --sdist
      - name: Check that tag version and sdist version match
        run: 'test -f dist/tensora-taco-${echo ${{ github.ref_name }} | cut -c 2-}.tar.gz'
      - name: Upload distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
            repository-url: https://test.pypi.org/legacy/